import { Exercise } from "../types";

export const symaMaths: Exercise[] = [
  // Comptage
  { id: "s_m1", question: "Combien y a-t-il de pommes ? 🍎🍎🍎", options: ["2", "3", "4", "1"], correct: 1 },
  { id: "s_m2", question: "Quel chiffre vient après 4 ?", options: ["3", "6", "5", "2"], correct: 2 },
  { id: "s_m3", question: "1 + 1 = ?", options: ["3", "2", "1", "4"], correct: 1 },
  { id: "s_m4", question: "Combien font 2 + 2 ?", options: ["3", "5", "4", "6"], correct: 2 },
  { id: "s_m5", question: "Quelle forme est un cercle ? ⭕🔺🟦🔶", options: ["🔺", "⭕", "🟦", "🔶"], correct: 1 },
  { id: "s_m6", question: "Quel chiffre est le plus grand : 3 ou 7 ?", options: ["3", "7", "Pareil", "Je sais pas"], correct: 1 },
  { id: "s_m7", question: "Combien font 3 + 1 ?", options: ["2", "3", "5", "4"], correct: 3 },
  { id: "s_m8", question: "Combien y a-t-il d'étoiles ? ⭐⭐⭐⭐⭐", options: ["4", "6", "3", "5"], correct: 3 },
  { id: "s_m9", question: "2 + 3 = ?", options: ["4", "5", "6", "3"], correct: 1 },
  { id: "s_m10", question: "Quel chiffre vient avant 8 ?", options: ["9", "6", "7", "5"], correct: 2 },
  { id: "s_m11", question: "Combien y a-t-il de ballons ? 🎈🎈🎈🎈", options: ["3", "5", "4", "2"], correct: 2 },
  { id: "s_m12", question: "1 + 2 = ?", options: ["2", "4", "3", "5"], correct: 2 },
  { id: "s_m13", question: "Quel chiffre est le plus petit : 2 ou 9 ?", options: ["9", "2", "Pareil", "5"], correct: 1 },
  { id: "s_m14", question: "Combien font 4 + 2 ?", options: ["5", "7", "6", "8"], correct: 2 },
  { id: "s_m15", question: "Quel chiffre vient après 6 ?", options: ["5", "8", "7", "9"], correct: 2 },
  { id: "s_m16", question: "Combien y a-t-il de cœurs ? ❤️❤️", options: ["3", "1", "2", "4"], correct: 2 },
  { id: "s_m17", question: "3 + 3 = ?", options: ["5", "7", "6", "4"], correct: 2 },
  { id: "s_m18", question: "Quel chiffre vient avant 5 ?", options: ["6", "3", "4", "2"], correct: 2 },
  { id: "s_m19", question: "Combien font 5 + 1 ?", options: ["5", "7", "6", "8"], correct: 2 },
  { id: "s_m20", question: "Combien y a-t-il de fleurs ? 🌸🌸🌸🌸🌸🌸", options: ["5", "7", "6", "4"], correct: 2 },
  { id: "s_m21", question: "Quelle forme a 4 côtés égaux ? 🔺🟦⭕🔷", options: ["🔺", "⭕", "🟦", "🔷"], correct: 2 },
  { id: "s_m22", question: "2 + 4 = ?", options: ["5", "7", "6", "8"], correct: 2 },
  { id: "s_m23", question: "Quel chiffre vient après 9 ?", options: ["8", "11", "10", "12"], correct: 2 },
  { id: "s_m24", question: "Combien font 1 + 0 ?", options: ["2", "0", "1", "3"], correct: 2 },
  { id: "s_m25", question: "Quel est le plus grand : 5 ou 8 ?", options: ["5", "8", "Pareil", "6"], correct: 1 },
  { id: "s_m26", question: "Combien y a-t-il de soleil ? ☀️", options: ["2", "1", "3", "0"], correct: 1 },
  { id: "s_m27", question: "4 + 4 = ?", options: ["6", "9", "8", "7"], correct: 2 },
  { id: "s_m28", question: "Quel chiffre vient avant 10 ?", options: ["8", "11", "9", "7"], correct: 2 },
  { id: "s_m29", question: "Combien font 3 + 2 ?", options: ["4", "6", "5", "7"], correct: 2 },
  { id: "s_m30", question: "Combien y a-t-il de chats ? 🐱🐱🐱", options: ["2", "4", "3", "1"], correct: 2 },
  { id: "s_m31", question: "Quel chiffre est entre 4 et 6 ?", options: ["3", "7", "5", "8"], correct: 2 },
  { id: "s_m32", question: "1 + 3 = ?", options: ["3", "5", "4", "2"], correct: 2 },
  { id: "s_m33", question: "Quel est le plus petit : 7 ou 3 ?", options: ["7", "3", "Pareil", "5"], correct: 1 },
  { id: "s_m34", question: "Combien font 5 + 2 ?", options: ["6", "8", "7", "9"], correct: 2 },
  { id: "s_m35", question: "Combien y a-t-il de lunettes dans ce nombre : 👓👓👓👓?", options: ["3", "5", "4", "2"], correct: 2 },
  { id: "s_m36", question: "2 + 2 + 1 = ?", options: ["4", "6", "5", "3"], correct: 2 },
  { id: "s_m37", question: "Quel chiffre vient après 2 ?", options: ["1", "4", "3", "5"], correct: 2 },
  { id: "s_m38", question: "Combien font 0 + 4 ?", options: ["3", "5", "4", "0"], correct: 2 },
  { id: "s_m39", question: "Quelle forme est un triangle ? ⭕🔺🟦🔶", options: ["⭕", "🔺", "🟦", "🔶"], correct: 1 },
  { id: "s_m40", question: "Quel chiffre est le plus grand : 1 ou 10 ?", options: ["1", "10", "Pareil", "5"], correct: 1 },
  { id: "s_m41", question: "3 + 4 = ?", options: ["6", "8", "7", "5"], correct: 2 },
  { id: "s_m42", question: "Combien y a-t-il de pingouins ? 🐧🐧🐧🐧🐧🐧🐧", options: ["6", "8", "7", "5"], correct: 2 },
  { id: "s_m43", question: "Quel chiffre vient avant 3 ?", options: ["4", "1", "2", "5"], correct: 2 },
  { id: "s_m44", question: "Combien font 2 + 6 ?", options: ["7", "9", "8", "6"], correct: 2 },
  { id: "s_m45", question: "Quel est le plus grand : 0 ou 5 ?", options: ["0", "5", "Pareil", "3"], correct: 1 },
];

export const symaFrancais: Exercise[] = [
  { id: "s_f1", question: "Quelle lettre fait le son [A] ?", options: ["B", "A", "C", "D"], correct: 1 },
  { id: "s_f2", question: "🐱 C'est un...", options: ["Chien", "Lapin", "Chat", "Oiseau"], correct: 2 },
  { id: "s_f3", question: "Quelle image correspond à 'MAISON' ?", options: ["🚗", "🏠", "🌳", "🐶"], correct: 1 },
  { id: "s_f4", question: "Quelle lettre fait le son [O] ?", options: ["A", "E", "I", "O"], correct: 3 },
  { id: "s_f5", question: "🐶 C'est un...", options: ["Chat", "Cheval", "Chien", "Cochon"], correct: 2 },
  { id: "s_f6", question: "Combien de syllabes dans 'PA-PA' ?", options: ["1", "3", "2", "4"], correct: 2 },
  { id: "s_f7", question: "Quelle lettre est la première de l'alphabet ?", options: ["B", "Z", "A", "M"], correct: 2 },
  { id: "s_f8", question: "🌞 C'est le...", options: ["Lune", "Soleil", "Nuage", "Étoile"], correct: 1 },
  { id: "s_f9", question: "Quel mot rime avec 'CHAT' ?", options: ["Chien", "Rat", "Lapin", "Oiseau"], correct: 1 },
  { id: "s_f10", question: "Quelle lettre fait le son [I] ?", options: ["A", "I", "O", "U"], correct: 1 },
  { id: "s_f11", question: "🍎 C'est une...", options: ["Poire", "Banane", "Pomme", "Orange"], correct: 2 },
  { id: "s_f12", question: "Combien de syllabes dans 'MA-MAN' ?", options: ["1", "3", "2", "4"], correct: 2 },
  { id: "s_f13", question: "Quel mot rime avec 'LUNE' ?", options: ["Soleil", "Étoile", "Dune", "Nuage"], correct: 2 },
  { id: "s_f14", question: "🐘 C'est un...", options: ["Lion", "Tigre", "Éléphant", "Girafe"], correct: 2 },
  { id: "s_f15", question: "Quelle lettre fait le son [U] ?", options: ["O", "I", "U", "A"], correct: 2 },
  { id: "s_f16", question: "Quel mot rime avec 'GÂTEAU' ?", options: ["Maison", "Château", "Jardin", "École"], correct: 1 },
  { id: "s_f17", question: "🌹 C'est une...", options: ["Tulipe", "Marguerite", "Rose", "Violette"], correct: 2 },
  { id: "s_f18", question: "Combien de syllabes dans 'CA-NA-RD' ?", options: ["1", "2", "3", "4"], correct: 1 },
  { id: "s_f19", question: "Quelle lettre fait le son [E] ?", options: ["A", "E", "I", "O"], correct: 1 },
  { id: "s_f20", question: "🐟 C'est un...", options: ["Chien", "Chat", "Poisson", "Lapin"], correct: 2 },
  { id: "s_f21", question: "Quel mot rime avec 'PAIN' ?", options: ["Manger", "Main", "Table", "Eau"], correct: 1 },
  { id: "s_f22", question: "🚗 C'est une...", options: ["Moto", "Voiture", "Vélo", "Avion"], correct: 1 },
  { id: "s_f23", question: "Combien de syllabes dans 'É-LÈ-VE' ?", options: ["1", "2", "3", "4"], correct: 2 },
  { id: "s_f24", question: "Quelle lettre vient après A dans l'alphabet ?", options: ["C", "B", "D", "Z"], correct: 1 },
  { id: "s_f25", question: "Quel mot rime avec 'BEAU' ?", options: ["Laid", "Gros", "Eau", "Froid"], correct: 2 },
  { id: "s_f26", question: "🌈 C'est un/une...", options: ["Nuage", "Soleil", "Arc-en-ciel", "Pluie"], correct: 2 },
  { id: "s_f27", question: "Combien de syllabes dans 'LI-ON' ?", options: ["1", "2", "3", "4"], correct: 1 },
  { id: "s_f28", question: "🍓 C'est une...", options: ["Pomme", "Poire", "Fraise", "Cerise"], correct: 2 },
  { id: "s_f29", question: "Quel mot rime avec 'SOURIS' ?", options: ["Lapin", "Riz", "Chien", "Chat"], correct: 1 },
  { id: "s_f30", question: "Quelle lettre est la dernière de l'alphabet ?", options: ["X", "Y", "Z", "W"], correct: 2 },
  { id: "s_f31", question: "🦁 C'est un...", options: ["Tigre", "Lion", "Léopard", "Guépard"], correct: 1 },
  { id: "s_f32", question: "Combien de syllabes dans 'CHO-CO-LAT' ?", options: ["1", "2", "3", "4"], correct: 2 },
  { id: "s_f33", question: "Quel mot rime avec 'BLEU' ?", options: ["Rouge", "Vert", "Feu", "Noir"], correct: 2 },
  { id: "s_f34", question: "🎂 C'est un...", options: ["Pain", "Gâteau", "Biscuit", "Bonbon"], correct: 1 },
  { id: "s_f35", question: "Quelle lettre fait le son [P] dans 'PAPA' ?", options: ["B", "D", "P", "T"], correct: 2 },
  { id: "s_f36", question: "🌊 C'est la...", options: ["Rivière", "Piscine", "Mer", "Lac"], correct: 2 },
  { id: "s_f37", question: "Combien de syllabes dans 'A-MI' ?", options: ["1", "2", "3", "4"], correct: 1 },
  { id: "s_f38", question: "Quel mot rime avec 'NUIT' ?", options: ["Jour", "Soir", "Pluie", "Matin"], correct: 2 },
  { id: "s_f39", question: "🐝 C'est une...", options: ["Fourmi", "Coccinelle", "Abeille", "Mouche"], correct: 2 },
  { id: "s_f40", question: "Quelle lettre fait le son [M] dans 'MAMAN' ?", options: ["N", "M", "B", "P"], correct: 1 },
  { id: "s_f41", question: "🎀 C'est un/une...", options: ["Ruban", "Nœud", "Ruban nœud", "Cadeau"], correct: 1 },
  { id: "s_f42", question: "Combien de syllabes dans 'BÉ-BÉ' ?", options: ["1", "2", "3", "4"], correct: 1 },
  { id: "s_f43", question: "Quel mot rime avec 'ÉCOLE' ?", options: ["Maison", "Drôle", "Jardin", "Classe"], correct: 1 },
  { id: "s_f44", question: "🦋 C'est un/une...", options: ["Abeille", "Libellule", "Papillon", "Coccinelle"], correct: 2 },
  { id: "s_f45", question: "Quelle lettre fait le son [V] dans 'VÉLO' ?", options: ["B", "F", "V", "W"], correct: 2 },
];

export const symaAnglais: Exercise[] = [
  { id: "s_a1", question: "🔴 In English, red is...", options: ["Blue", "Green", "Red", "Yellow"], correct: 2 },
  { id: "s_a2", question: "🐱 In English, 'chat' is...", options: ["Dog", "Cat", "Bird", "Fish"], correct: 1 },
  { id: "s_a3", question: "How do you say 'bonjour' in English?", options: ["Goodbye", "Thank you", "Hello", "Please"], correct: 2 },
  { id: "s_a4", question: "🍎 In English, 'pomme' is...", options: ["Banana", "Orange", "Apple", "Grape"], correct: 2 },
  { id: "s_a5", question: "How do you count to 3? 1, 2, ___", options: ["Four", "Five", "Two", "Three"], correct: 3 },
  { id: "s_a6", question: "🔵 This color in English is...", options: ["Red", "Blue", "Green", "Yellow"], correct: 1 },
  { id: "s_a7", question: "🐶 In English, 'chien' is...", options: ["Cat", "Dog", "Fish", "Bird"], correct: 1 },
  { id: "s_a8", question: "How do you say 'au revoir' in English?", options: ["Hello", "Please", "Goodbye", "Yes"], correct: 2 },
  { id: "s_a9", question: "🌟 This is a...", options: ["Moon", "Sun", "Star", "Cloud"], correct: 2 },
  { id: "s_a10", question: "How many? 1, 2, 3, 4, ___", options: ["Six", "Three", "Five", "Seven"], correct: 2 },
  { id: "s_a11", question: "🟡 This color in English is...", options: ["Red", "Blue", "Green", "Yellow"], correct: 3 },
  { id: "s_a12", question: "🐟 In English, 'poisson' is...", options: ["Bird", "Cat", "Fish", "Dog"], correct: 2 },
  { id: "s_a13", question: "How do you say 'merci' in English?", options: ["Please", "Thank you", "Sorry", "Hello"], correct: 1 },
  { id: "s_a14", question: "🍌 In English, 'banane' is...", options: ["Apple", "Orange", "Banana", "Grape"], correct: 2 },
  { id: "s_a15", question: "How do you say 'oui' in English?", options: ["No", "Yes", "Maybe", "Please"], correct: 1 },
  { id: "s_a16", question: "🟢 This color in English is...", options: ["Red", "Blue", "Green", "Yellow"], correct: 2 },
  { id: "s_a17", question: "🐠 In English, this animal is a...", options: ["Shark", "Whale", "Fish", "Dolphin"], correct: 2 },
  { id: "s_a18", question: "How do you say 'non' in English?", options: ["Yes", "No", "Maybe", "Please"], correct: 1 },
  { id: "s_a19", question: "🏠 In English, 'maison' is...", options: ["School", "Garden", "House", "Park"], correct: 2 },
  { id: "s_a20", question: "1, 2, 3, 4, 5. What comes next?", options: ["7", "8", "6", "9"], correct: 2 },
  { id: "s_a21", question: "⚪ This color in English is...", options: ["Black", "Grey", "White", "Pink"], correct: 2 },
  { id: "s_a22", question: "🐠 In English, 'orange' (the fruit) is...", options: ["Lemon", "Apple", "Orange", "Mango"], correct: 2 },
  { id: "s_a23", question: "How do you say 's'il vous plaît' in English?", options: ["Thank you", "Please", "Sorry", "Hello"], correct: 1 },
  { id: "s_a24", question: "🌞 In English, 'soleil' is...", options: ["Moon", "Star", "Cloud", "Sun"], correct: 3 },
  { id: "s_a25", question: "⚫ This color in English is...", options: ["White", "Grey", "Brown", "Black"], correct: 3 },
  { id: "s_a26", question: "🐦 In English, 'oiseau' is...", options: ["Cat", "Dog", "Bird", "Fish"], correct: 2 },
  { id: "s_a27", question: "How do you say 'école' in English?", options: ["Home", "Park", "School", "Shop"], correct: 2 },
  { id: "s_a28", question: "🍇 In English, 'raisin' (the fruit) is...", options: ["Cherry", "Apple", "Peach", "Grape"], correct: 3 },
  { id: "s_a29", question: "How do you say 'maman' in English?", options: ["Sister", "Dad", "Mum", "Brother"], correct: 2 },
  { id: "s_a30", question: "🐰 In English, 'lapin' is...", options: ["Hamster", "Rabbit", "Mouse", "Cat"], correct: 1 },
  { id: "s_a31", question: "What color is the sky? 🌈", options: ["Red", "Green", "Yellow", "Blue"], correct: 3 },
  { id: "s_a32", question: "🍓 In English, 'fraise' is...", options: ["Cherry", "Raspberry", "Strawberry", "Peach"], correct: 2 },
  { id: "s_a33", question: "How do you say 'papa' in English?", options: ["Mum", "Brother", "Dad", "Uncle"], correct: 2 },
  { id: "s_a34", question: "🌙 In English, 'lune' is...", options: ["Star", "Moon", "Sun", "Cloud"], correct: 1 },
  { id: "s_a35", question: "How many fingers on one hand? One, two, three, four, ___", options: ["Six", "Seven", "Five", "Eight"], correct: 2 },
  { id: "s_a36", question: "🐮 In English, 'vache' is...", options: ["Horse", "Cow", "Pig", "Sheep"], correct: 1 },
  { id: "s_a37", question: "🟣 This color in English is...", options: ["Pink", "Blue", "Purple", "Red"], correct: 2 },
  { id: "s_a38", question: "How do you say 'je t'aime' in English?", options: ["I miss you", "I love you", "I like you", "I see you"], correct: 1 },
  { id: "s_a39", question: "🐷 In English, 'cochon' is...", options: ["Cow", "Sheep", "Pig", "Horse"], correct: 2 },
  { id: "s_a40", question: "🍰 In English, 'gâteau' is...", options: ["Bread", "Cake", "Cookie", "Pie"], correct: 1 },
  { id: "s_a41", question: "How do you say 'livre' in English?", options: ["Pen", "Paper", "Book", "Bag"], correct: 2 },
  { id: "s_a42", question: "🎈 In English, 'ballon' is...", options: ["Ball", "Balloon", "Kite", "Toy"], correct: 1 },
  { id: "s_a43", question: "What number is 'cinq' in English?", options: ["Four", "Six", "Five", "Three"], correct: 2 },
  { id: "s_a44", question: "🌺 In English, 'fleur' is...", options: ["Tree", "Grass", "Flower", "Leaf"], correct: 2 },
  { id: "s_a45", question: "🐸 In English, 'grenouille' is...", options: ["Snake", "Frog", "Lizard", "Turtle"], correct: 1 },
];
